export {
  COMPANY_STATUSES,
  DEPLOYMENT_MODES,
  DEPLOYMENT_EXPOSURES,
  AUTH_BASE_URL_MODES,
  AGENT_STATUSES,
  AGENT_ADAPTER_TYPES,
  AGENT_ICON_NAMES,
  ISSUE_STATUSES,
  ISSUE_PRIORITIES,
  GOAL_LEVELS,
  GOAL_STATUSES,
  PROJECT_STATUSES,
  PROJECT_COLORS,
  APPROVAL_TYPES,
  APPROVAL_STATUSES,
  SECRET_PROVIDERS,
  STORAGE_PROVIDERS,
  HEARTBEAT_INVOCATION_SOURCES,
  HEARTBEAT_RUN_STATUSES,
  WAKEUP_TRIGGER_DETAILS,
  WAKEUP_REQUEST_STATUSES,
  LIVE_EVENT_TYPES,
  PRINCIPAL_TYPES,
  MEMBERSHIP_STATUSES,
  INSTANCE_USER_ROLES,
  INVITE_TYPES,
  INVITE_JOIN_TYPES,
  JOIN_REQUEST_TYPES,
  JOIN_REQUEST_STATUSES,
  type CompanyStatus,
  type DeploymentMode,
  type DeploymentExposure,
  type AuthBaseUrlMode,
  type AgentStatus,
  type AgentAdapterType,
  type AgentIconName,
  type IssueStatus,
  type IssuePriority,
  type GoalLevel,
  type GoalStatus,
  type ProjectStatus,
  type ApprovalType,
  type ApprovalStatus,
  type SecretProvider,
  type StorageProvider,
  type HeartbeatInvocationSource,
  type HeartbeatRunStatus,
  type WakeupTriggerDetail,
  type WakeupRequestStatus,
  type LiveEventType,
  type PrincipalType,
  type MembershipStatus,
  type InstanceUserRole,
  type InviteType,
  type InviteJoinType,
  type JoinRequestType,
  type JoinRequestStatus,
} from "./constants.js";

// POD-01: Sandbox constants (renamed from pod)
export {
  SANDBOX_STATUSES,
  SANDBOX_CLAUDE_AUTH_STATUSES,
  // Backward-compatible aliases
  POD_STATUSES,
  POD_CLAUDE_AUTH_STATUSES,
} from "./types/index.js";
// DEPLOY-01: Deployment constants
export {
  DEPLOYMENT_STATUSES,
  DEPLOYMENT_PROJECT_TYPES,
} from "./types/index.js";

export type {
  Company,
  Agent,
  AgentPermissions,
  AgentKeyCreated,
  AgentConfigRevision,
  AdapterEnvironmentCheckLevel,
  AdapterEnvironmentTestStatus,
  AdapterEnvironmentCheck,
  AdapterEnvironmentTestResult,
  AssetImage,
  Project,
  ProjectGoalRef,
  ProjectWorkspace,
  Issue,
  IssueAssigneeAdapterOverrides,
  IssueComment,
  IssueAttachment,
  IssueLabel,
  Goal,
  Approval,
  ApprovalComment,
  CostEvent,
  CostSummary,
  CostByAgent,
  HeartbeatRun,
  HeartbeatRunEvent,
  AgentRuntimeState,
  AgentTaskSession,
  AgentWakeupRequest,
  LiveEvent,
  DashboardSummary,
  // DASH-S01: Dashboard API types
  DashboardPeriod,
  DashboardBreakdownCategory,
  DashboardKpis,
  DashboardTimelinePoint,
  DashboardTimeline,
  DashboardBreakdownItem,
  DashboardBreakdown,
  ActivityEvent,
  SidebarBadges,
  CompanyMembership,
  Invite,
  JoinRequest,
  InstanceUserRoleGrant,
  CompanyPortabilityInclude,
  CompanyPortabilitySecretRequirement,
  CompanyPortabilityCompanyManifestEntry,
  CompanyPortabilityAgentManifestEntry,
  CompanyPortabilityManifest,
  CompanyPortabilityExportResult,
  CompanyPortabilitySource,
  CompanyPortabilityImportTarget,
  CompanyPortabilityAgentSelection,
  CompanyPortabilityCollisionStrategy,
  CompanyPortabilityPreviewRequest,
  CompanyPortabilityPreviewAgentPlan,
  CompanyPortabilityPreviewResult,
  CompanyPortabilityImportRequest,
  CompanyPortabilityImportResult,
  CompanyPortabilityExportRequest,
  EnvBinding,
  AgentEnvConfig,
  CompanySecret,
  SecretProviderDescriptor,
  WorkspaceTask,
  AcceptanceCriterion,
  ContextNodeDetail,
  ContextNode,
  WorkspaceStory,
  WorkspaceEpic,
  WorkspaceStep,
  PlanningArtifact,
  SprintStatus,
  WorkspaceContext,
  // Legacy aliases
  BmadTask,
  BmadAcceptanceCriterion,
  BmadStory,
  BmadEpic,
  BmadPlanningArtifact,
  BmadSprintStatus,
  BmadProject,
  DriftSeverity,
  DriftType,
  DriftRecommendation,
  DriftDecision,
  DriftReportStatus,
  DriftItem,
  DriftReport,
  DriftCheckRequest,
  DriftResolveRequest,
  DriftScanRequest,
  DriftScanStatus,
  DriftReportFilters,
  DriftItemFilters,
  // DRIFT-S02: Drift monitor types
  DriftAlertType,
  DriftAlert,
  DriftMonitorConfig,
  DriftMonitorStatus,
  StageState,
  WorkflowState,
  StageEvent,
  StageContext,
  TransitionRecord,
  OrchestratorEvent,
  RequiredFileDef,
  FileCheckResult,
  EnforcementResult,
  StageArtifact,
  PrePromptPayload,
  HitlDecision,
  HitlValidationRequest,
  PendingValidation,
  AuditActorType,
  AuditSeverity,
  AuditTargetType,
  AuditAction,
  AuditEventInput,
  AuditEvent,
  AuditListResult,
  AuditVerifyResult,
  // OBS-S03: Audit summary types
  AuditSummaryPeriod,
  AuditSummarySource,
  AuditSummaryStats,
  AuditSummary,
  ChatChannelStatus,
  ChatSenderType,
  ChatMessageType,
  ChatClientMessage,
  ChatClientTyping,
  ChatClientSync,
  ChatClientPing,
  ChatClientPayload,
  ChatServerMessage,
  ChatServerAck,
  ChatServerTyping,
  ChatServerSync,
  ChatServerError,
  ChatServerPong,
  ChatServerChannelClosed,
  ChatServerPayload,
  // CHAT-S03: Container pipe types
  ContainerPipeStatus,
  ChatPipeStatus,
  ChatPipeAttachRequest,
  // COMP-S01: Compaction types
  // comp-s01-barrel-shared
  CompactionStrategy,
  CompactionSnapshotStatus,
  CompactionSnapshot,
  CompactionWatcherConfig,
  CompactionWatcherStatus,
  CompactionSnapshotFilters,
  // comp-s02-barrel-shared
  KillRelaunchResult,
  RelaunchHistoryEntry,
  RelaunchHistoryFilters,
  // comp-s03-barrel-shared
  ReinjectionResult,
  ReinjectionHistoryEntry,
  ReinjectionHistoryFilters,
  RecoveryPrompt,
  // DUAL-S01: Automation cursor types
  // dual-s01-barrel-shared
  AutomationCursorPosition,
  AutomationCursorLevel,
  AutomationCursor,
  EffectiveCursor,
  // dual-s03-barrel-shared
  CursorEnforcementResult,
  // A2A-S01: A2A Bus types
  // a2a-s01-barrel-shared
  A2AMessageType,
  A2AMessageStatus,
  A2AMessage,
  A2AChainInfo,
  A2AStats,
  A2AMessageFilters,
  // A2A-S02: A2A Permission types
  // a2a-s02-barrel-shared
  A2ADefaultPolicy,
  A2APermissionRule,
  A2APermissionCheckResult,
  // A2A-S03: Audit A2A type
  // a2a-s03-barrel-shared
  A2AAuditAction,
  // TRACE-01: Trace types
  TraceStatus,
  TraceObservationType,
  TraceObservationStatus,
  Trace,
  TraceObservation,
  TraceObservationNode,
  TraceWithTree,
  TraceListResult,
  TraceLensScope,
  TraceLens,
  TraceLensResult,
  // PIPE-03: Gold prompt types
  GoldPromptScope,
  GoldPrompt,
  // SSO-S01: SSO configuration types
  // sso-s01-barrel-shared
  SsoProvider,
  SsoConfigStatus,
  SsoConfiguration,
  CreateSsoConfigurationInput,
  UpdateSsoConfigurationInput,
  // SSO-S02: SSO auth flow types
  // sso-s02-barrel-shared
  SsoLoginInitiation,
  SsoDiscoverResult,
  SsoAuthResult,
  SsoSamlConfig,
  SsoOidcConfig,
  SsoMetadataSyncResult,
  // A2A-S04: MCP Connector types
  McpConnectorStatus,
  McpTransportType,
  McpConnector,
  McpTool,
  McpToolInvocationResult,
  McpConnectorTestResult,
  McpConnectorStats,
  McpConnectorFilters,
  // POD-01: Per-User Sandbox types (renamed from pod)
  SandboxStatus,
  SandboxClaudeAuthStatus,
  UserSandbox,
  SandboxProvisionOptions,
  // Backward-compatible aliases
  PodStatus,
  PodClaudeAuthStatus,
  UserPod,
  PodProvisionOptions,
  // DEPLOY-01: Artifact Deployment types
  DeploymentStatus,
  DeploymentProjectType,
  ArtifactDeployment,
  DeploymentCreateOptions,
  // config-layer-barrel-shared
  ConfigLayerItemType,
  ConfigLayerScope,
  ConfigLayerVisibility,
  ConfigLayerSourceType,
  McpCredentialProvider,
  McpCredentialStatus,
  ConfigLayer,
  ConfigLayerItem,
  ConfigLayerFile,
  ConfigLayerDetail,
  AgentConfigLayerAttachment,
  ConfigLayerRevision,
  ConflictSeverity,
  ConfigLayerConflict,
  ConflictCheckResult,
  MergedConfigItem,
  MergePreviewResult,
  UserMcpCredential,
  // CHAT-ARTIFACTS: Artifact types
  ArtifactType,
  Artifact,
  ArtifactVersion,
  // CHAT-COLLAB: Document, folder, sharing types
  IngestionStatus,
  Document,
  DocumentChunk,
  FolderVisibility,
  FolderItemType,
  Folder,
  FolderItem,
  SharePermission,
  ContextLinkType,
  ChatShare,
  ChatContextLink,
} from "./types/index.js";

export {
  STAGE_STATES,
  WORKFLOW_STATES,
  STAGE_EVENTS,
  AUDIT_ACTOR_TYPES,
  AUDIT_SEVERITY_LEVELS,
  AUDIT_TARGET_TYPES,
  AUDIT_ACTIONS,
  // OBS-S03: Audit summary constants
  AUDIT_SUMMARY_PERIODS,
  AUDIT_SUMMARY_SOURCES,
  // COMP-S01: Compaction constants
  COMPACTION_STRATEGIES,
  COMPACTION_SNAPSHOT_STATUSES,
  // DUAL-S01: Automation cursor constants
  AUTOMATION_CURSOR_POSITIONS,
  AUTOMATION_CURSOR_LEVELS,
  // A2A-S01: A2A Bus constants
  A2A_MESSAGE_TYPES,
  A2A_MESSAGE_STATUSES,
  // A2A-S02: A2A Permission constants
  A2A_DEFAULT_POLICIES,
  // A2A-S03: Audit A2A constants
  A2A_AUDIT_ACTIONS,
  // TRACE-01: Trace constants
  TRACE_STATUSES,
  TRACE_OBSERVATION_TYPES,
  TRACE_OBSERVATION_STATUSES,
  // PIPE-03: Gold prompt constants
  GOLD_PROMPT_SCOPES,
  // SSO-S01: SSO configuration constants
  SSO_PROVIDERS,
  SSO_CONFIG_STATUSES,
  // DASH-S01: Dashboard API constants
  DASHBOARD_PERIODS,
  DASHBOARD_BREAKDOWN_CATEGORIES,
  K_ANONYMITY_THRESHOLD,
} from "./types/index.js";

// config-layer constants (re-exported from validators for convenience)
export {
  CONFIG_LAYER_ITEM_TYPES,
  CONFIG_LAYER_SCOPES,
  CONFIG_LAYER_VISIBILITIES,
  CONFIG_LAYER_SOURCE_TYPES,
  CONFIG_LAYER_CHANGE_SOURCES,
  MCP_CREDENTIAL_PROVIDERS,
  MCP_CREDENTIAL_STATUSES,
  HOOK_EVENTS,
  HOOK_TYPES,
  SETTING_KEYS,
} from "./validators/index.js";

export {
  createCompanySchema,
  updateCompanySchema,
  type CreateCompany,
  type UpdateCompany,
  createAgentSchema,
  createAgentHireSchema,
  updateAgentSchema,
  updateAgentInstructionsPathSchema,
  createAgentKeySchema,
  wakeAgentSchema,
  resetAgentSessionSchema,
  testAdapterEnvironmentSchema,
  agentPermissionsSchema,
  updateAgentPermissionsSchema,
  type CreateAgent,
  type CreateAgentHire,
  type UpdateAgent,
  type UpdateAgentInstructionsPath,
  type CreateAgentKey,
  type WakeAgent,
  type ResetAgentSession,
  type TestAdapterEnvironment,
  type UpdateAgentPermissions,
  createProjectSchema,
  updateProjectSchema,
  createProjectWorkspaceSchema,
  updateProjectWorkspaceSchema,
  type CreateProject,
  type UpdateProject,
  type CreateProjectWorkspace,
  type UpdateProjectWorkspace,
  createIssueSchema,
  createIssueLabelSchema,
  updateIssueSchema,
  checkoutIssueSchema,
  addIssueCommentSchema,
  linkIssueApprovalSchema,
  createIssueAttachmentMetadataSchema,
  type CreateIssue,
  type CreateIssueLabel,
  type UpdateIssue,
  type CheckoutIssue,
  type AddIssueComment,
  type LinkIssueApproval,
  type CreateIssueAttachmentMetadata,
  createGoalSchema,
  updateGoalSchema,
  type CreateGoal,
  type UpdateGoal,
  createApprovalSchema,
  resolveApprovalSchema,
  requestApprovalRevisionSchema,
  resubmitApprovalSchema,
  addApprovalCommentSchema,
  type CreateApproval,
  type ResolveApproval,
  type RequestApprovalRevision,
  type ResubmitApproval,
  type AddApprovalComment,
  envBindingPlainSchema,
  envBindingSecretRefSchema,
  envBindingSchema,
  envConfigSchema,
  createSecretSchema,
  rotateSecretSchema,
  updateSecretSchema,
  type CreateSecret,
  type RotateSecret,
  type UpdateSecret,
  createCostEventSchema,
  updateBudgetSchema,
  createAssetImageMetadataSchema,
  scopeSchema,
  resourceScopeSchema,
  type PermissionScope,
  type ResourceScope,
  createCompanyInviteSchema,
  createOpenClawInvitePromptSchema,
  acceptInviteSchema,
  listJoinRequestsQuerySchema,
  claimJoinRequestApiKeySchema,
  updateMemberPermissionsSchema,
  updateUserCompanyAccessSchema,
  type CreateCostEvent,
  type UpdateBudget,
  type CreateAssetImageMetadata,
  type CreateCompanyInvite,
  type CreateOpenClawInvitePrompt,
  type AcceptInvite,
  type ListJoinRequestsQuery,
  type ClaimJoinRequestApiKey,
  type UpdateMemberPermissions,
  type UpdateUserCompanyAccess,
  portabilityIncludeSchema,
  portabilitySecretRequirementSchema,
  portabilityCompanyManifestEntrySchema,
  portabilityAgentManifestEntrySchema,
  portabilityManifestSchema,
  portabilitySourceSchema,
  portabilityTargetSchema,
  portabilityAgentSelectionSchema,
  portabilityCollisionStrategySchema,
  companyPortabilityExportSchema,
  companyPortabilityPreviewSchema,
  companyPortabilityImportSchema,
  type CompanyPortabilityExport,
  type CompanyPortabilityPreview,
  type CompanyPortabilityImport,
  workflowStageTemplateDefSchema,
  createWorkflowTemplateSchema,
  updateWorkflowTemplateSchema,
  createWorkflowInstanceSchema,
  updateWorkflowInstanceSchema,
  transitionStageSchema,
  updateStageSchema,
  type CreateWorkflowTemplate,
  type UpdateWorkflowTemplate,
  type CreateWorkflowInstance,
  type UpdateWorkflowInstance,
  type TransitionStage,
  type UpdateStage,
  PROJECT_MEMBERSHIP_ROLES,
  addProjectMemberSchema,
  updateProjectMemberRoleSchema,
  bulkAddProjectMembersSchema,
  bulkRemoveProjectMembersSchema,
  memberCountsSchema,
  type ProjectMembershipRole,
  type AddProjectMember,
  type UpdateProjectMemberRole,
  type BulkAddProjectMembers,
  type BulkRemoveProjectMembers,
  type MemberCounts,
  auditEventFiltersSchema,
  auditExportFiltersSchema,
  auditVerifySchema,
  type AuditEventFilters,
  type AuditExportFilters,
  type AuditVerifyParams,
  // OBS-S03: Audit summary validators
  auditSummaryFiltersSchema,
  auditSummaryGenerateSchema,
  type AuditSummaryFilters,
  type AuditSummaryGenerate,
  orchestratorTransitionSchema,
  orchestratorApproveSchema,
  orchestratorRejectSchema,
  orchestratorCheckEnforcementSchema,
  orchestratorWorkflowFilterSchema,
  orchestratorStageFilterSchema,
  type OrchestratorTransition,
  type OrchestratorApprove,
  type OrchestratorReject,
  type OrchestratorCheckEnforcement,
  type OrchestratorWorkflowFilter,
  type OrchestratorStageFilter,
  // COMP-S01: Compaction validators
  startCompactionWatcherSchema,
  compactionSnapshotFiltersSchema,
  type StartCompactionWatcher,
  type CompactionSnapshotFiltersInput,
  // COMP-S02: Kill+Relaunch validators
  // comp-s02-barrel-validators-shared
  killRelaunchSchema,
  relaunchHistoryFiltersSchema,
  type KillRelaunchInput,
  type RelaunchHistoryFiltersInput,
  // COMP-S03: Reinjection validators
  // comp-s03-barrel-validators-shared
  reinjectionSchema,
  reinjectionHistoryFiltersSchema,
  type ReinjectionInput,
  type ReinjectionHistoryFiltersInput,
  // DUAL-S01: Automation cursor validators
  setCursorSchema,
  cursorFiltersSchema,
  resolveCursorSchema,
  type SetCursor,
  type CursorFilters,
  type ResolveCursor,
  // A2A-S01: A2A Bus validators
  sendA2AMessageSchema,
  respondA2AMessageSchema,
  a2aMessageFiltersSchema,
  type SendA2AMessage,
  type RespondA2AMessage,
  type A2AMessageFiltersInput,
  // A2A-S02: A2A Permission validators
  // a2a-s02-barrel-validators-shared
  createA2APermissionRuleSchema,
  updateA2APermissionRuleSchema,
  updateA2ADefaultPolicySchema,
  type CreateA2APermissionRule,
  type UpdateA2APermissionRule,
  type UpdateA2ADefaultPolicy,
  // DASH-S01: Dashboard validators
  // dash-s01-barrel-validators-shared
  dashboardTimelineFiltersSchema,
  dashboardBreakdownCategorySchema,
  type DashboardTimelineFilters,
  type DashboardBreakdownCategoryInput,
  // SSO-S01: SSO configuration validators
  // sso-s01-barrel-validators-shared
  createSsoConfigurationSchema,
  updateSsoConfigurationSchema,
  type CreateSsoConfiguration,
  type UpdateSsoConfiguration,
  // SSO-S02: SSO auth validators
  // sso-s02-barrel-validators-shared
  ssoDiscoverSchema,
  ssoSamlConfigSchema,
  ssoOidcConfigSchema,
  type SsoDiscover,
  type SsoSamlConfigInput,
  type SsoOidcConfigInput,
  // TRACE: Trace validators
  createTraceSchema,
  completeTraceSchema,
  createObservationSchema,
  batchCreateObservationsSchema,
  completeObservationSchema,
  traceListFiltersSchema,
  createTraceLensSchema,
  updateTraceLensSchema,
  // PIPE-03: Gold prompt validators
  createGoldPromptSchema,
  updateGoldPromptSchema,
  goldPromptFiltersSchema,
  type CreateTrace,
  type CompleteTrace,
  type CreateObservation,
  type BatchCreateObservations,
  type CompleteObservation,
  type TraceListFilters,
  type CreateTraceLens,
  type UpdateTraceLens,
  // PIPE-03: Gold prompt types
  type CreateGoldPrompt,
  type UpdateGoldPrompt,
  type GoldPromptFilters,
  // A2A-S04: MCP Connector validators
  createMcpConnectorSchema,
  updateMcpConnectorSchema,
  mcpConnectorFiltersSchema,
  invokeMcpToolSchema,
  type CreateMcpConnector,
  type UpdateMcpConnector,
  type InvokeMcpTool,
  // CHAT-ARTIFACTS: Artifact validators
  ARTIFACT_TYPES,
  createArtifactSchema,
  updateArtifactSchema,
  type CreateArtifact,
  type UpdateArtifact,
  // config-layer validators
  mcpItemConfigSchema,
  skillItemConfigSchema,
  hookItemConfigSchema,
  settingItemConfigSchema,
  createConfigLayerSchema,
  updateConfigLayerSchema,
  createConfigLayerItemSchema,
  updateConfigLayerItemSchema,
  createConfigLayerFileSchema,
  attachConfigLayerSchema,
  approvePromotionSchema,
  rejectPromotionSchema,
  type McpItemConfig,
  type SkillItemConfig,
  type HookItemConfig,
  type SettingItemConfig,
  type CreateConfigLayer,
  type UpdateConfigLayer,
  type CreateConfigLayerItem,
  type UpdateConfigLayerItem,
  type CreateConfigLayerFile,
  type AttachConfigLayer,
  type ApprovePromotion,
  type RejectPromotion,
  // FOLDERS: Folder validators
  FOLDER_VISIBILITIES,
  FOLDER_ITEM_TYPES,
  createFolderSchema,
  updateFolderSchema,
  addFolderItemSchema,
  type CreateFolder,
  type UpdateFolder,
  type AddFolderItem,
  // CHAT-SHARING: Share + context link validators
  SHARE_PERMISSIONS,
  CONTEXT_LINK_TYPES,
  createShareSchema,
  addContextLinkSchema,
  type CreateShare,
  type AddContextLink,
} from "./validators/index.js";

// REMOVED: rbac-presets.ts and role-hierarchy.ts — replaced by dynamic roles in DB

// onb-s03-barrel-shared
export type {
  ImportJobStatus,
  JiraImportConfig,
  JiraImportPreview,
  JiraImportProgress,
} from "./jira-import-types.js";

export { API_PREFIX, API } from "./api.js";
export { normalizeAgentUrlKey, deriveAgentUrlKey, isUuidLike } from "./agent-url-key.js";
export { deriveProjectUrlKey, normalizeProjectUrlKey } from "./project-url-key.js";
export {
  PROJECT_MENTION_SCHEME,
  buildProjectMentionHref,
  parseProjectMentionHref,
  extractProjectMentionIds,
  type ParsedProjectMention,
} from "./project-mentions.js";

export {
  mnmConfigSchema,
  configMetaSchema,
  llmConfigSchema,
  databaseBackupConfigSchema,
  databaseConfigSchema,
  loggingConfigSchema,
  serverConfigSchema,
  authConfigSchema,
  secretsConfigSchema,
  storageConfigSchema,
  storageLocalDiskConfigSchema,
  storageS3ConfigSchema,
  secretsLocalEncryptedConfigSchema,
  type MnMConfig,
  type LlmConfig,
  type DatabaseBackupConfig,
  type DatabaseConfig,
  type LoggingConfig,
  type ServerConfig,
  type AuthConfig,
  type StorageConfig,
  type StorageLocalDiskConfig,
  type StorageS3Config,
  type SecretsConfig,
  type SecretsLocalEncryptedConfig,
  type ConfigMeta,
} from "./config-schema.js";
